changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Site Development
      labels:
        - site
    - title: Documentation Maintenance
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"