on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TOC_TITLE: '## 目次(Toc)'
          COMMIT_MESSAGE: 'feat: update Toc'
          TARGET_PATHS:
            documentation/*